const { raw } = require('express');
const express = require('express');



const app = express();
const port = 3000;

app.use(express.static('public'))
app.use(express.static('private'))
app.use(express.urlencoded({ extended: false}))

function htmlStart(res)
{
    res.write(`<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>`);
}

function htmlEnd(res) 
{
    console.log("sending");
    res.write(`</body>
    </html>`);
    res.end();

};


app.get('/', async (req, res) => {

    res.write(`<a href="/loc">Locations</a>`)



    try {
    htmlStart(res);
    res.write(`<h1>This page is generated by the server</h1>`)
    res.write(`<a href="/page.html">Go to Static Page</a>`)


// fetch(`https://rickandmortyapi.com/api/character/`).then(fRes => {
//         return fRes.json();
// }).then(data => {
//     for (let person of data.results) {
//         res.write(`<h1>${person.name}</h1>`)
//     }
//     htmlEnd(res);

// })
// .catch(err => {
//     res.write(`<h1>Uh Oh: ${err.message}`);
//     htmlEnd(res);
// })


// let fRes = await fetch(`https://rickandmortyapi.com/api/character`);
// let data = await fRes.json();

// for (let person of data.results) {
//     res.write(`<h1>${person.name}: ${person.gender}, found ${person.location.name}</h1>`)
// };

// htmlEnd(res)
//     }
//     catch (err) {
//         res.write(`<h1>Uh oh: ${err.message}`);
//         htmlEnd(res);
//     }

// })

let fRes = await fetch(`https://rickandmortyapi.com/api/location/1`);
let data = await fRes.json();
console.log(data.residents);

// res.write(`${data.residents[1]}`)

res.write(`<h1>Residents of ${data.name}:`);


for (let person of data.residents) {
    console.log(person)
    let aRes = await fetch(person)
    let aData = await aRes.json();
    console.log(aData.name)

    // res.write(`<h1>Residents of ${data.name}:`);
    // for (let guy in aData) {
        res.write(`<p>${aData.name}</p>`);
    // }
    // for (let guy of aData)
    // res.write(`<h1>${person.name}: ${person.gender}, found ${person.location.name}</h1>`)
    // console.log(data.residents[person])
};

htmlEnd(res)
    }
    catch (err) {
        res.write(`<h1>Uh oh: ${err.message}`);
        htmlEnd(res);
    }

})

app.get('/loc', async (req, res) => {
    htmlStart(res);
    try {
        let bRes = await fetch(`https://rickandmortyapi.com/api/location`)
        let bData = await bRes.json();

        // console.log(bData.info.count);

        for(let i = 1; i <= bData.info.count; i++) {
            let tRes = await fetch(`https://rickandmortyapi.com/api/location/${i}`);
            let tData = await tRes.json();
            // console.log(tData);
            res.write(`<h2>${tData.name}</h2>`)
            res.write(`<ul>`);
            for(let person of tData.residents) {
                let nRes = await fetch(person);
                let nData = await nRes.json();
                // console.log(nData);
                res.write(`<li>${nData.name}</li>`)
            }
            res.write(`</ul>`);

        }

        htmlEnd(res);

    }
    catch (err) {
        res.write(`<h1>Uh oh: ${err.message}`);
        htmlEnd(res);
    }

})



app.listen(port, () => {
    console.log(`I'm listening!!!! (on port: ${port})`);
});